parameters:
    redis.service_name: 'redis'
    process.id: 0

services:
    redis:
        factory: 'Symfony\Component\DependencyInjection\ContainerInterface:get'
        arguments:
            - '%redis.service_name%'

    instagram.client.http:
        public: true
        class: xyz13\InstagramBundle\Client\HttpClient

    xyz13\InstagramBundle\Instagram\Factory:
        class: xyz13\InstagramBundle\Instagram\Factory
        arguments:
            - "@redis"
            - "@kernel"
            - "@instagram.client.http"
            - "%process.id%"

    instagram.web_driver:
        class: xyz13\InstagramBundle\Instagram\Instagram
        public: true
        factory: 'xyz13\InstagramBundle\Instagram\Factory:create'

    instagram.web_driver.logger:
        class: Monolog\Logger
        arguments: ["instagram.web_driver.logger"]
        calls:
          - [pushHandler, ["@instagram.web_driver.stream_handler"]]

    instagram.web_driver.stream_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.web_driver.log, 100]